version: 2
jobs:
  build:
    docker:
      - image: 'node:10'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: yarn build
